{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chatroom-server.serviceAccountName" . }}
  labels:
{{ include "chatroom-server.labels" . | nindent 4 }}
{{- end -}}
