{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chatroom.serviceAccountName" . }}
  namespace: foo
  labels:
{{ include "chatroom.labels" . | nindent 4 }}
{{- end -}}
