apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatroom.fullname" . }}
  namespace: foo
  labels:
    {{- include "chatroom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "chatroom.selectorLabels" . | nindent 4 }}
